# Generated by Django 2.2.1 on 2019-09-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_name', models.CharField(max_length=264)),
                ('brand', models.CharField(choices=[('TOY', 'Toyota'), ('MZD', 'Mazda'), ('LXS', 'Lexus'), ('BMW', 'BMW'), ('PRS', 'Porsche'), ('MCB', 'Mercedes-Benz'), ('HND', 'Honda'), ('NSN', 'Nissan'), ('MBS', 'Mitsubishi'), ('CVL', 'Chevrolet'), ('FRD', 'Ford'), ('HYD', 'Hyundai')], max_length=1)),
                ('type', models.CharField(max_length=264)),
                ('car_model', models.CharField(max_length=264)),
                ('year', models.CharField(max_length=264)),
                ('transmission', models.CharField(choices=[('AT', 'Automatic'), ('MT', 'Manual')], max_length=1)),
                ('owners_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
