# Generated by Django 2.2.1 on 2019-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ_SellMyCar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('TOY', 'Toyota'), ('MZD', 'Mazda'), ('LXS', 'Lexus'), ('BMW', 'BMW'), ('PRS', 'Porsche'), ('MCB', 'Mercedes-Benz'), ('HND', 'Honda'), ('NSN', 'Nissan'), ('MBS', 'Mitsubishi'), ('CVL', 'Chevrolet'), ('FRD', 'Ford'), ('HYD', 'Hyundai')], max_length=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('AT', 'Automatic'), ('MT', 'Manual')], max_length=2),
        ),
    ]
