# Generated by Django 2.2.1 on 2019-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ_SellMyCar', '0002_auto_20190930_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('TOY', 'Toyota'), ('MZD', 'Mazda'), ('LXS', 'Lexus'), ('BMW', 'BMW'), ('PRS', 'Porsche'), ('MCB', 'Mercedes-Benz'), ('HND', 'Honda'), ('NSN', 'Nissan'), ('MBS', 'Mitsubishi'), ('CVL', 'Chevrolet'), ('FRD', 'Ford'), ('HYD', 'Hyundai')], max_length=3),
        ),
    ]
